### ISSUE TITLE
Generate new fileindex.msf or new .mrf(003,004)

### ISSUE THREAD

**Issue by josepwb** [toptaran/rzpacker#2]
Hello, you can add a option to generate a new fileindex.msf reading the folders, or atleast new .mrf's (002,003,004 etc) , Updater of Launcher dont work after the .mrf reach 500mb+ sometimes, then a possibility to create new files would be cool and solve this problem

Thanks Again, also thanks for the generate keys update !

**Comment by RobinsonLeoTiradoCelis** [comment]
Hello, the unpacker don't  work for client Revolution Riderz, when I try to unpack the client got this error in console "Fileindex decrypt error!
and Fileindex read/parse error!, hope you can provide support for this client too. Thanks for the tool!

**Comment by josepwb** [comment]
you wil

> Hello, the unpacker don't work for client Revolution Riderz, when I try to unpack the client got this error in console "Fileindex decrypt error!
> and Fileindex read/parse error!, hope you can provide support for this client too. Thanks for the tool!

That will not work for revolution raiderz, its my server we changed encrypt.

**Comment by sc1066** [comment]
Hello!  I want to knows how to generate new keys?

Try it many times and it doesn't work

**Comment by temtriss** [comment]
Hey, yea that feature will be awesome. you can just add file size limit? so if it more then 300mb, do next one then rebuild indexfile

**Comment by josepwb** [comment]
Toptaran we need a little help here my friend xD, we want create a fileindex.msf from scratch or add new .mrf files or .001~.007 to fileindex.msf but our Java knowledge are really crap, can you please help us?

**Comment by toptaran** [comment]
Resolved
