### ISSUE TITLE
Unpacker error

### ISSUE THREAD

**Issue by RobinsonLeoTiradoCelis** [toptaran/rzpacker#3]
Hello, the unpacker don't  work for client Revolution Riderz, when I try to unpack the client got this error in console "Fileindex decrypt error!
and Fileindex read/parse error!, hope you can provide support for this client too. Thanks for the tool!
This is the fileindex.msf : https://www.mediafire.com/file/1pz22wpbyiolca1/fileindex.msf/file

**Comment by josepwb** [comment]
You can't unpack revolution, its with different encryption already.

**Comment by RobinsonLeoTiradoCelis** [comment]
Surely Toptaran can.

**Comment by josepwb** [comment]
And why you need unpack my client? ._. create your own files lol

**Comment by RobinsonLeoTiradoCelis** [comment]
I don't have a raiderz server, I just want to see some models. Be calm...

**Comment by toptaran** [comment]
It's not an error of packer, just use correct keys.
