### ISSUE TITLE
Make a rzpacker for NA client (end of 2014 client)

### ISSUE THREAD

**Issue by CarIosBR** [toptaran/rzpacker#4]
Hello, i don't know how to enter in contact with you, this is my discord CarlosBR#3026, Please chat me there about what i said in the title of this issue and thank you.

**Comment by toptaran** [comment]
> Hello, i don't know how to enter in contact with you, this is my discord CarlosBR#3026, Please chat me there about what i said in the title of this issue and thank you.

Hello,
do you have launcher.exe and recovery.exe from last na client version?

**Comment by CarIosBR** [comment]
> > Hello, i don't know how to enter in contact with you, this is my discord CarlosBR#3026, Please chat me there about what i said in the title of this issue and thank you.
> 
> Hello, do you have launcher.exe and recovery.exe from last na client version?

Hello, do you have any news ?

**Comment by toptaran** [comment]
Done in version 2.0
