### ISSUE TITLE
Version Upgrade

### ISSUE THREAD

**Issue by josepwb** [toptaran/rzpacker#5]
Hello again, thank you for the recent implementation to create new .mrf, but again I have some doubts, the current system of RZPACKER is a complete suite for maintenance and creation of new contents in RaiderZ, however it is limited to the version of the end of 2012 (aka "Bolas Version Cap 35") there is the possibility of migrating the tool to the latest version of RaiderZ (2014) in which the PWE/WMO/KR servers closed, we just have the keys for unpack this 2014 version, so have no idea if its possible such implementation on current tool.
I am anxiously awaiting your reply.

Best Regards,
José Lucas

**Comment by toptaran** [comment]
Hello,
do you have launcher.exe and recovery.exe from last na client version?

**Comment by toptaran** [comment]
> Hello again, thank you for the recent implementation to create new .mrf, but again I have some doubts, the current system of RZPACKER is a complete suite for maintenance and creation of new contents in RaiderZ, however it is limited to the version of the end of 2012 (aka "Bolas Version Cap 35") there is the possibility of migrating the tool to the latest version of RaiderZ (2014) in which the PWE/WMO/KR servers closed, we just have the keys for unpack this 2014 version, so have no idea if its possible such implementation on current tool. I am anxiously awaiting your reply.
> 
> Best Regards, José Lucas

Hello,
do you have launcher.exe and recovery.exe from last na client version?

**Comment by josepwb** [comment]
[files.zip](https://github.com/toptaran/rzpacker/files/11619389/files.zip)
Hello,
this ones are Launcher and Recovery from NA/Steam Version

**Comment by toptaran** [comment]
Done in version 2.0
