### ISSUE TITLE
Problem on Launcher after PatchALL

### ISSUE THREAD

**Issue by josepwb** [toptaran/rzpacker#9]
![image](https://github.com/toptaran/rzpacker/assets/11277702/90a37056-4312-48eb-8071-921ace62be7a)
Hello again, after patchall on all files, game works normally all others files changed the key/encryption normally, but when try open the Launcher i'm getting this error, i'm doing something wrong? 

Best Regards,
José Lucas

**Comment by toptaran** [comment]
Hello,
depends on launcher i think. I tested it on launcher provided in Issue #5

**Comment by josepwb** [comment]
Wierd, tried on this same launcher that got uploaded for you and isnt working, can you upload here the launcher.exe for check please?

**Comment by toptaran** [comment]
I took latest NA client from ragezone, renamed Raidrz_mc to Raiderz, added here launcher and recovery from zip of issue 5.
Download and unpack rzpacker2 from release, changed in startpatchall batch file place of raiderz client.
Launched it, after patch start launcher, all is ok.
[RaiderZ NA.zip](https://github.com/toptaran/rzpacker/files/14759781/RaiderZ.NA.zip)
![image](https://github.com/toptaran/rzpacker/assets/3803872/bea04c6b-d4bf-447c-94ba-22a06f412bd1)

**Comment by toptaran** [comment]
You can decrypt launcher dat file using startdecrypt batch from release version of rzpacker.

**Comment by josepwb** [comment]
With your upload it worked, but looks like Launcher dont read the buildver file , the Key of it remains the same ? because on KEys file it still using PWEBuildverKey

**Comment by josepwb** [comment]
![image](https://github.com/toptaran/rzpacker/assets/11277702/9baec71c-4953-46e0-966b-7d0e280460b8)
this error to be exact.

**Comment by josepwb** [comment]
![image](https://github.com/toptaran/rzpacker/assets/11277702/d9b0b453-3eb1-4272-b57d-19ed1e546e91)
Using the files you provided the .dat become with 1kb only didnt know why also

**Comment by toptaran** [comment]
![image](https://github.com/toptaran/rzpacker/assets/3803872/20efe189-82d9-42d1-920e-60ec4ec4fc4f)
Make temp web server, checked all is ok, buildver checked correctly.

Patch function work only for original files, you can't change keys in same file few times. Every time need to take original files.

**Comment by josepwb** [comment]
> ![image](https://private-user-images.githubusercontent.com/3803872/316908557-20efe189-82d9-42d1-920e-60ec4ec4fc4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjQ1NTksIm5iZiI6MTcxMTQ2NDI1OSwicGF0aCI6Ii8zODAzODcyLzMxNjkwODU1Ny0yMGVmZTE4OS04MmQ5LTQyZDEtOTIwZS02MGVjNGVjNGZjNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMTQ0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRjMjg2MzA0N2MyZGIwNTQ2NTIyYTRhMmEwYzU2MWY2ZWYzZDNjYWJhYTNjZjliOWQwY2YwOWRlNjNlYTczYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NzFup1L-MjJoqY1JOx-1S_WboYSG2b6fcgheFyJc4Ho) Make temp web server, checked all is ok, buildver checked correctly.
> 
> Patch function work only for original files, you can't change keys in same file few times. Every time need to take original files.

I know just can use one time on the original file, but after downloaded the files you send the raiderz launcher.dat become 1kb after the patchall and on promp it show the key isnt located on executable file of Launcher

**Comment by toptaran** [comment]
Another thing I assume you maybe think wrong about Private.key and PrivateVer2.key.
For ver2 it need both, new ver2 key using solely for fileindex, for other files still using ver1 key.

**Comment by toptaran** [comment]
> > ![image](https://private-user-images.githubusercontent.com/3803872/316908557-20efe189-82d9-42d1-920e-60ec4ec4fc4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjQ1NTksIm5iZiI6MTcxMTQ2NDI1OSwicGF0aCI6Ii8zODAzODcyLzMxNjkwODU1Ny0yMGVmZTE4OS04MmQ5LTQyZDEtOTIwZS02MGVjNGVjNGZjNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMTQ0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRjMjg2MzA0N2MyZGIwNTQ2NTIyYTRhMmEwYzU2MWY2ZWYzZDNjYWJhYTNjZjliOWQwY2YwOWRlNjNlYTczYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NzFup1L-MjJoqY1JOx-1S_WboYSG2b6fcgheFyJc4Ho) Make temp web server, checked all is ok, buildver checked correctly.
> > Patch function work only for original files, you can't change keys in same file few times. Every time need to take original files.
> 
> I know just can use one time on the original file, but after downloaded the files you send the raiderz launcher.dat become 1kb after the patchall and on promp it show the key isnt located on executable file of Launcher

But I sent you already patched files. Original ones you can take in Issue #5.

**Comment by josepwb** [comment]
Oh ok it must work now, i did some mistake in middle of alot of files, gonna try and check everything here now, thanks in advance!

**Comment by toptaran** [comment]
No new info, I assume problem solved.
